remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [John Shelburne On Github]
description: [An attempt to use Github Pages as a personal site which will teach me a little version control]
