description: John Shelburne's Homepage
logo: /assets/img/funlogo.gif
remote_theme: pages-themes/minimal@v0.2.0
email: jshelburne@gmail.com
github_username: thecatfix
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
