remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Work In Progress
description: An attempt to use Github Pages as a personal site.
