theme: jekyll-theme-jsblog
remote_theme:
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-paginate
- jekyll-sitemap
title: [John Shelburne On Github]
description: [An attempt to use Github Pages as a personal site which will teach me a little version control]
base_url: "thecatfix.github.io"


permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5